package com.example.subsapp.model

import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import com.example.subsapp.R

object FakeAnimeData {

    val dummyAnimeList = listOf(
        Anime(1, R.drawable.onepiece, "One Piece" , 150000, "One Piece (Jepang: ワンピース, Hepburn: Wan Pīsu) adalah sebuah seri manga Jepang yang ditulis dan diilustrasikan oleh Eiichiro Oda. Manga ini telah dimuat di majalah Weekly Shōnen Jump milik Shueisha sejak tanggal 22 Juli 1997, dan telah dibundel menjadi 105 volume tankōbon hingga Maret 2023. Ceritanya mengisahkan petualangan Monkey D. Luffy, seorang anak laki-laki yang memiliki kemampuan tubuh elastis seperti karet setelah memakan Buah Iblis secara tidak disengaja. Luffy bersama kru bajak lautnya, yang dinamakan Bajak Laut Topi Jerami, menjelajahi Grand Line untuk mencari harta karun terbesar di dunia yang dikenal sebagai \"One Piece\" dalam rangka untuk menjadi Raja Bajak Laut yang berikutnya"),
        Anime(2, R.drawable.attackontitan, "Attack On Titan" , 100000, "Shingeki no Kyojin (bahasa Jepang: 進撃の巨人, terj. har. \"Raksasa [yang] Menyerang\"), yang diterbitkan di Indonesia dengan judul Attack on Titan, adalah sebuah seri manga shōnen asal Jepang yang ditulis dan diilustrasikan oleh Hajime Isayama. Ceritanya berlatar di dunia tempat umat manusia hidup di wilayah yang dikelilingi tiga lapis tembok besar, yang melindungi mereka dari makhluk pemakan manusia berukuran raksasa yang dikenal sebagai Titan." ),
        Anime(3, R.drawable.demonslayer, "Demon Slayer", 90000,"Kimetsu no Yaiba (Jepang: 鬼滅の刃, terj. har. \"Korps Pembasmi Iblis\"[4]), yang diterbitkan di Indonesia dengan judul Demon Slayer: Kimetsu no Yaiba, adalah sebuah seri manga Jepang yang ditulis dan diilustrasikan oleh Koyoharu Gotōge. Ceritanya mengisahkan tentang Tanjiro Kamado, seorang anak laki-laki yang menjadi pembasmi iblis setelah keluarganya dibantai oleh iblis dan adik perempuannya yang bernama Nezuko diubah menjadi iblis. Manga ini dimuat berseri dalam majalah Weekly Shōnen Jump terbitan Shueisha sejak bulan Februari 2016 hingga Mei 2020, dan telah dibundel menjadi dua puluh satu volume tankōbon hingga bulan Juli 2020."),
        Anime(4, R.drawable.detektifconan, "Detektif Conan", 80000,"Detektif Conan (名探偵コナン, Meitantei Konan), yang juga dikenal sebagai Case Closed dan Detective Conan, adalah seri manga detektif Jepang yang ditulis dan diilustrasikan oleh Gosho Aoyama. Serial ini diserialisasikan dalam majalah manga shōnen Weekly Shōnen Sunday yang diterbitkan oleh Shogakukan sejak Januari 1994, dengan bab-babnya"),
        Anime(5, R.drawable.jujutsu, "Jujutsu Kaisen" ,70000,"Jujutsu Kaisen (Jepang: 呪術廻戦, terj. har. \"Pertarungan Sihir\") adalah sebuah seri manga shōnen asal Jepang yang ditulis dan diilustrasikan oleh Gege Akutami. Manga ini dimuat berseri dalam majalah Weekly Shōnen Jump terbitan Shueisha sejak Maret 2018, dan telah diterbitkan menjadi dua puluh empat volume tankōbon per Oktober 2023"),
        Anime(6, R.drawable.naruto, "Naruto", 75000,"Naruto (ナルト) adalah sebuah serial manga karya Masashi Kishimoto yang diadaptasi menjadi serial anime. Manga Naruto bercerita seputar kehidupan tokoh utamanya, Naruto Uzumaki, seorang ninja yang hiperaktif, periang, dan ambisius yang ingin mewujudkan keinginannya untuk mendapatkan gelar Hokage, pemimpin dan ninja terkuat di desanya. Serial ini didasarkan pada komik one-shot oleh Kishimoto yang diterbitkan dalam edisi Akamaru Jump pada Agustus 1997."),
        Anime(7, R.drawable.onepunchman, "One Punch Man", 70000,"One Punch Man ( ワンパンマン Pria Satu Pukulan) adalah sebuah serial manga Jepang yang menceritakan seorang superhero yang bernama Saitama. One-Punch Man dibuat oleh seorang penulis yang asal jepang dengan nama samaran ONE[1] yang mulai diterbitkan pada awal tahun 2009.[2] Serial ini menjadi viral sehingga mampu melampaui 7,9 juta penggemar pada bulan Juni 2012.[3] One-Punch Man merupakan kontraksi wanpanchi (\"One-Punch\") yang artinya satu pukulan.[4]"),
        Anime(8, R.drawable.castlevania, "CastleVania: Nocturne", 65000,"Castlevania: Nocturne is an American adult animated dark fantasy action streaming television series created and written by Clive Bradley and produced by Kevin Kolde for Netflix. A spin-off and a stand-alone sequel to the animated series Castlevania, it is based on the Japanese video game series of the same name by Konami and loosely adapted from Castlevania: Rondo of Blood (1993) and its sequel Symphony of the Night (1997), as well as story elements from Harmony of Dissonance (2002)"),
        Anime(9, R.drawable.mushoku, "Mushoku Tensei", 60000,"Mushoku Tensei: Isekai Ittara Honki Dasu (Jepang: 無職転生 〜異世界行ったら本気だす〜) adalah sebuah seri novel ringan Jepang yang ditulis oleh Rifujin na Magonote. Mengisahkan tentang seorang pria pengangguran dan putus asa yang bereinkarnasi ke dunia fantasi sambil mempertahankan ingatannya, ia bertekad untuk menjalani kehidupan barunya tanpa penyesalan. Seri ini awalnya diterbitkan di situs web berisi novel karya penggunanya Shōsetsuka ni Narō pada tanggal 22 November 2012"),
        Anime(10, R.drawable.spyx, "Spy X Family", 70000,"Spy × Family (Jepang: スパイファミリー) adalah sebuah seri manga web shōnen Jepang yang ditulis dan diilustrasikan oleh Tatsuya Endō (遠藤達哉). Manga ini mulai dimuat pada platform Shōnen Jump+ milik Shueisha sejak tanggal 25 Maret 2019, dan telah dibundel menjadi dua belas volume tankōbon. Shueisha mulai merilis seri ini dalam bahasa Inggris secara serentak dengan perilisannya di Jepang melalui platform Manga Plus sejak bulan Maret 2019. Adaptasi serial televisi anime oleh Wit Studio dan CloverWorks ditayangkan perdana pada April 2022 di Netflix")
    )

}